# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# See yaml syntax: https://learnxinyminutes.com/yaml/
#

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Checkout repository https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops
#                  & https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines
- checkout: self
  path: mySource  # in absense of this line, the source is put in $(Agent.BuildDirectory)/s/ directory
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo 'myPassword=$(myPassword)
    ls
    pwd
    echo '$(Agent.BuildDirectory)'
    cat ./test.sql
    cat '$(Agent.BuildDirectory)/mySource/test.sql'
  displayName: 'Run a multi-line script'
